### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by gvsurenderreddy** [isayme/go-wstunnel#1]
Hello sir 
How to use local and server and you share few examples if possible that would be nice

**Comment by isayme** [comment]
see https://github.com/isayme/go-wstunnel/tree/master/example for example configure.

**Comment by isayme** [comment]
see https://github.com/isayme/go-wstunnel/tree/master/example for example configure.

**Comment by isayme** [comment]
see https://github.com/isayme/go-wstunnel/tree/master/example for example configure.
